### ISSUE TITLE
[feat] 자동 반복 챌린지 생성을 위한 auto_challenge 테이블 구현

### ISSUE THREAD

**Issue by zyu22** [clapsheep/WalkOrRun-server#68]
## 📝 작업 내용
1. auto_challenge 테이블 생성
   - [x] 반복 챌린지의 자동 생성을 관리하기 위한 새로운 테이블 구현
   - [x] 기존 challenge 테이블과의 연관 관계 설정
   - [x] 반복 주기(daily/weekly/monthly) 플래그 필드 추가

2. 자동 생성 로직 구현
   - [x] 관리자가 반복 챌린지 생성 시 스케쥴링이 반복 시간이 되면, auto_challenge 테이블에 자동 등록되는 쿼리 작성
   - [x] 반복 주기별로 적절한 플래그 설정
   - [x] 기존 challenge 테이블과 연동

## 💬 요구사항
1. auto_challenge를 insert 할 테이블 명을 추천해주실 수 있을까요?
2. auto_challenge에 들어 갈 flag 칼럼 명은 무엇이 좋을까요?

**Comment by yujeong789** [comment]
1. Auto_Challenge
2. period
